### ISSUE TITLE
Data outputs from the model

### ISSUE THREAD

**Issue by billlyzhaoyh** [nt409/AI-for-good#6]
In order to have the flexibility for our front-end visualisation choices, we can stream out the data produced from baseline models and models from interventions as one CSV file or multiple CSV files.

The files will have S, E, I, R population count at each time step (per day) for each model run thus enable flexible options for our front-end choices.

**Comment by nt409** [comment]
Have created a function which converts model outputs into csvs, currently maintaining age structure (although this could be changed so that each category is reported across the entire age demographic instead/as well)

**Comment by nt409** [comment]
Now added percentiles as well as including demographic level output for normal solution (that is, now have summary of e.g. susceptible people by summing over all age categories)
